openapi: "3.0.0"
info:
  title: App API documentation
  version: 1.0.0
servers:
  - url: http://127.0.0.1:8000/api/v1
paths:
  /bodykit-shops:
    get:
      description: List all bodykit shops
      responses:
        '200':
          description: List of bodykit shops
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/BodykitShop"
    post:
      description: Creates new bodykit shop
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewBodykitShop"
      responses:
        '201':
          description: Successfully created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BodykitShop"
        '400':
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /bodykit-shops/{id}:
    parameters:
        - name: id
          in: path
          description: bodykit shop ID
          required: true
          schema:
            type: integer
            format: int64
    get:
      description: Get bodykit shop with specified ID
      responses:
        '200':
          description: Bodykit with specified id
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BodykitShop"
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /bodykits:
    get:
      description: Gets all bodykits
      responses:
        '200':
          description: List of bodykits
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Bodykit"
    post:
      description: Creates bodykit
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewBodykit"
      responses:
        '201':
          description: Successfully created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Bodykit"
        '400':
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /bodykits/{id}:
    parameters:
      - name: id
        in: path
        description: bodykit ID
        required: true
        schema:
          type: integer
          format: int64
    get:
      description: Gets bodykit with specified ID
      responses:
        '200':
          description: Bodykit with specified ID
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Bodykit"
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      description: Deletes bodykit with specified ID
      responses:
        '200':
          description: Successfully deleted
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    put:
      description: Replaces bodykit with specified ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewBodykit"
      responses:
        '200':
          description: Successfully updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Bodykit"
        '400':
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    patch:
      description: Updates bodykit with specified ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BodykitPatch"
      responses:
        '200':
          description: Successfully updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Bodykit"
        '400':
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    BodykitShop:
      allOf:
        - $ref: '#/components/schemas/NewBodykitShop'
        - type: object
          required:
            - id
          properties:
            id:
              type: integer
              format: int64
    NewBodykitShop:
      type: object
      required:
        - name
        - address
        - bodykit_capacity
      properties:
        name:
          type: string
        address:
          type: string
        bodykit_capacity:
          type: integer
          format: int64

    Bodykit:
      allOf:
        - $ref: '#/components/schemas/NewBodykit'
        - type: object
          required:
            - id
          properties:
            id:
              type: integer
              format: int64
    NewBodykit:
      allOf:
        - $ref: '#/components/schemas/BodykitPatch'
        - type: object
          required:
            - version
            - name
            - manufacture_year
            - bodykit_shop_id
    BodykitPatch:
      type: object
      properties:
        version:
          type: string
        name:
          type: string
        manufacture_year:
          type: integer
          format: int64
        bodykit_shop_id:
          type: integer
          format: int64
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
